github: [NormikChel, Normik-Chel]
patreon: NormikChel
buy_me_a_coffee: normikchel
thanks_dev:
  - https://github.com/Normik-Chel
  - https://github.com/NormikChel
  - https://github.com/NormikChel-MinecraftFun
  - https://normikchel.github.io
  - https://normikchel.linkpc.net
  - https://gemeratorotmazok.neocities.org
  - https://normik-chel.github.io
custom: 
  - https://www.donationalerts.com/r/normik_chel
  - http://boosty.to/NormikChel/donate
  - https://new.donatepay.ru/@NormikChel
  - https://memealerts.com/NormikChel
